### ISSUE TITLE
TcpServer.Listen(port) dualstack does not throw SocketException(AddressAlreadyInUse)

### ISSUE THREAD

**Issue by mkm-ar** [CaveSystems/cave-tcpserver#1]
**Bug:**
`TcpServer.Listen(port)` allows to bind to a port (ipv6 dualstack) another (ipv4) socket/listener is already bound to without throwing any error.
This behaviour is unwanted because no ipv4 connection can be accepted.

**Proposed Bugfix:**
Set `Socket.ExclusiveAddressUse = true` by default

**Comment by Dingsd4** [comment]
Solution:
TcpServer gets a property ExclusiveAddressUse with default value true.

**Comment by Dingsd4** [comment]
Fixed in v1.0.3
